services:
  go:
    build: docker/go
    volumes:
      - ./langs/go:/src
    env_file:
      - .env

  node:
    build: docker/node
    volumes:
      - ./langs/node:/src
    env_file:
      - .env

  php:
    build: docker/php
    volumes:
      - ./langs/php:/src
      - ./data/composer:/root/.composer
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./data/xdebug:/xdebug
    ports:
      - $DOCKER_PHP_PUBLIC_PORT:80
    env_file:
      - .env
