services:
  go:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    volumes:
      - ./langs/go:/src
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./langs/node:/src
