services:
  go:
    build: docker/go
    volumes:
      - ./langs/go:/src
    env_file:
      - .env

  node:
    build: docker/node
    volumes:
      - ./langs/node:/src
    env_file:
      - .env

  php:
    build: docker/php
    volumes:
      - ./langs/php:/src
      - ./data/composer:/root/.composer
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./data/xdebug:/xdebug
    ports:
      - $DOCKER_PHP_PUBLIC_PORT:80
    env_file:
      - .env

  postgres:
    image: postgres:16.3
    ports:
      - $DOCKER_POSTGRES_PUBLIC_PORT:5432
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PSQL_HISTORY=/var/lib/postgresql/history/postgres
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
      - ./data/postgres-psql-history:/var/lib/postgresql/history
